name: Get list of modified EE

# Description:
# 
# This workflow run based on a "push" from branch development or feat/<feature-name>      #
#   First, it checks for any changes made in "aap-azure" folder,                          #
#   then it build the ee on the aap-azure-dev environment                                 #
#   finally it open a pull request towards the production branch if                       #
###########################################################################################

on:
  push:
    branches: [ "feat/build-workflow" ]
    paths:

      - 'aap-azure/**/*' # Trigger the workflow for any changes under the aap-azure/ directory
      - 'aap-onprem/**/*'
      - 'config/**/*'
      - '!aap-azure/**/CHANGELOG'  # Ignore this specific file
      - '!aap-onprem/**/CHANGELOG'  # Ignore this specific file 

  workflow_dispatch:

 

jobs:

  generate-matrix-ee:
    runs-on: ubuntu-latest
        # ['self-hosted', 'Linux', 'ephemeral']
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      ischangedA: ${{ steps.change-in-aapazure.outputs.ischangedA }}
      filecontent: ${{ steps.matrix.outputs.filecontent }}

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0  # Fetch all history so we can access HEAD~1
       
        - name: Set up python3
          uses: actions/setup-python@v5
 
        - name: Get list of modified files in last commit
          id: modified_files
          run: |
            MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD  | grep '^config/' )
            echo "Modified Files:"
            echo "$MODIFIED_FILES"
            echo "files=$MODIFIED_FILES" >> $GITHUB_OUTPUT

        - name: Save modified files list to a file
          run: |
           echo "${{ steps.modified_files.outputs.files }}" > modified_files_list.txt

        # - name: Upload modified files list as artifact
        #   uses: actions/upload-artifact@v3
        #   with:
        #     name: modified-files-list
        #     path: modified_files_list.txt

        - name: Create the matrix json file
          run: |
            echo "DISPLAY MATRIX "
            cat ./config/matrix.json


        # - name: Call the reusable workflow  # FAILED because it is interpreted as a composite actions
        #   uses: ./.github/workflows/reusable_workflow.yml
        #   with:
        #     matrix_path: ./config/matrix.json

        # - name: call the workflow
        #   run : |

        #     echo "1 Ref name ${{ github.ref_name }}"; echo "2Full ref ${{github.ref}}"
        #     echo "tonton" > matrix.json

        #     matrix_content=$(cat ./config/matrix.json)

        #     gh workflow run reusable_workflow.yml --field matrix_path="${matrix_content}" --ref ${{github.ref_name }}
    

        # - name: Display list of changed files

        #   if: ${{ steps.change-in-aapazure.outputs.ischangedA == 'True' }}

        #   run: |
        #     echo "display  content fo file"
        #     pwd
        #     ls -lha
        #     cat /tmp/modified-folders.txt

        # - name: Generate a matrix of modfiied ee to use.
        #   id: matrix
        #   if: ${{ steps.change-in-aapazure.outputs.ischangedA == 'True' }}
        #   run: |
        #     echo "Generate matrix of modified EE."
        #     python3 ./.github/workflows/scripts/ee-generate-matrix.py /tmp/modified-folders.txt ./config/aap-azure/list-ee-azure.yml matrix.json
        #     echo -e "########## \n"
        #     echo "Content of Matrix generated \n"
        #     echo "filecontent=$(cat matrix.json | base64 -w 0)" >> $GITHUB_ENV
        

        # - name: Upload artifact
        #   if: ${{ steps.change-in-aapazure.outputs.ischangedA == 'True' }}
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: matrixfile
        #     path: ./matrix.json

        
        # - name: display internal
        #   run : |
        #     echo ${{ steps.matrix.outputs.filecontent }}

 